INSERT INTO orders(seq, total_price, waiter) VALUES(0,200,'Gary')
INSERT INTO orders(seq, total_price, waiter) VALUES(1,170,'Jason')
INSERT INTO meals(id, name, price, description) VALUES(0,'burger', 150, 'Tasty')
INSERT INTO meals(id, name, price, description) VALUES(1,'cake', 100, 'Sweet')
INSERT INTO meals(id, name, price, description) VALUES(2,'fries',50, 'oil')
INSERT INTO meals(id, name, price, description) VALUES(3,'coffee', 70, 'good')
INSERT INTO order_meal(order_seq, meal_id) VALUES(0, 0)
INSERT INTO order_meal(order_seq, meal_id) VALUES(0, 2)
INSERT INTO order_meal(order_seq, meal_id) VALUES(1, 1)
INSERT INTO order_meal(order_seq, meal_id) VALUES(1, 3)